### ISSUE TITLE
Does not execute with my statements

### ISSUE THREAD

**Issue by beslu** [angelo-mollame/batch-replacer#1]
Issue Type: <b>Bug</b>

Hi, 

trying to do some batch update on a xml file 

---------------
replace "id=SR-11699|layout=160" 
with "id=SR-11699|layout=3"

replace "id=SR-11701|layout=163" 
with "id=SR-11701|layout=3"

replace "id=SR-11702|layout=164" 
with "id=SR-11702|layout=3"
----------------------------------

File is in workspace, result is "Batch replace completed: 0 file(s) modified.."

As I generate the replace-statements using formulas in Excel, it would be nice if the statements could be written on one line like:

replace "id=SR-11706|layout=168" with "id=SR-11706|layout=3"

It is difficult to put in CrLF with excel and paste to a text editor.

Regards, 
Bent

Extension version: 1.2.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.66GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by v-kistai** [comment]
I'm having this issue too.
Nothing I try to replace results in any change "Batch replace completed: 0 file(s) modified.."

**Comment by angelo-mollame** [comment]
The one-line format...

```
replace "id=SR-11706|layout=168" with "id=SR-11706|layout=3"
```

... is not supported by the extension. 

There is an easy way to solve your problem. In Visual Studio Code, you can select one of the "with", and then go to Selection > Select All Occurrences (or press CTRL+SHIFT+L). This will select all occurrences of "with". Then you can move to the right spot through the arrow keys and press ENTER to break the line in the right spot, in all those lines at once.
