### ISSUE TITLE
Question: How to batch-replace files with different extensions?

### ISSUE THREAD

**Issue by RieksJ** [angelo-mollame/batch-replacer#12]
Suppose I want to execute a replace script on all files that have any of the following extensions: `.txt`, `.src`, `.ifc`, `.test`, `.tst`.
Of course, I can create a script that changes all `.txt` files, and then repeat it for the other extensions, but that quickly becomes quite cumbersome. Is there a way to use the `filter` and `in` commands to specify e.g. `*.txt; *.src; *.ifc, *.test, *.tst`? I've tried to find out from the source code, but my typescript is too bad...

**Comment by RieksJ** [comment]
Found it: globs can be listed. For example, if I want to change all files with extensions `*.txt` and `*.src`, the filter command that would do it reads:

`filter "**/*.txt, **/*.src"`

**Comment by AccuBytes-TimJ** [comment]
This doesn't seem to work anymore.  I tried with the exact same syntax as you did, and it changed 0 files.
Also, the filter is case sensitive, so you need *.csv AND *.CSV.  It would be great to add mutiple filters and have them case insensitive.
