### ISSUE TITLE
Unable to batch replace

### ISSUE THREAD

**Issue by ZhuningS** [angelo-mollame/batch-replacer#5]
solved

**Comment by netowp** [comment]
What did you do? The extension does not work me and I have no idea why (no errors... nothing happens).

**Comment by ArturoDent** [comment]
Yes, same here  Error message:

> Failed to parse the script. Unrecognized instruction at line 1: Alice

with `Alice` in a file.

[What filename/extension should the script be saved as, and where?]

**Comment by angelo-mollame** [comment]
What script were you trying to use?

**Comment by ArturoDent** [comment]
Using this script.  And a `.txt` file with `Alice` in it.
```
replace "Alice"
with "Bob"

replace "Carol"
with "David"
```

Okay, I apparently figured it out.  I was saving the "script" file with a filename and then trying to run it while focus was on the file to be changed.  Both mistakes.  I would suggest that you edit the instructions to reflect both things.  

I would like to save the "script" file so it can be reused.  I tried that and with it focussed it works but the script file itself was changed.  I don't immediately see a way to filter out the script file itself from being changed.

**Comment by angelo-mollame** [comment]
That script should work.

The error you posted ("Unrecognized instruction at line 1: Alice") seems to indicate that you were using a script with a line containing just Alice.

You need to run the command when the script file is open, not when the file you're trying to modify is open.

**Comment by ArturoDent** [comment]
See https://stackoverflow.com/a/62786994/836330 (Regex matching to change ES module import to direct import) for a usage of Batch Replacer.  Thank you. Angelo.
